//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewQA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acomment
    {
        public int id { get; set; }
        public int answer_id { get; set; }
        public string body { get; set; }
        public int user_id { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
