//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewQA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QADBEntities : DbContext
    {
        public QADBEntities()
            : base("name=QADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acomment> Acomment { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<AppUser> AppUser { get; set; }
        public virtual DbSet<Qcomment> Qcomment { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<Tag_Question> Tag_Question { get; set; }
        public virtual DbSet<Qvote> Qvote { get; set; }
        public virtual DbSet<Avote> Avote { get; set; }
    }
}
